const bcrypt = require('bcryptjs');

module.exports = {
  up: (QueryInterface) => QueryInterface.bulkInsert(
    'users',
    [
      {
        name: 'Vinicius',
        email: 'viniolic@email.com',
        password_hash: bcrypt.hashSync('0000', 8),
        is_ong: false,
        state: 'MG',
        city: 'Ipatinga',
        image: 'http://pm1.narvii.com/6619/cccda6f18583df1e4c6e1fe57d21320371cab360_00.jpg',
        phone: 31992324515,
        latitude: '-19.483520',
        longitude: '-42.515887',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'Zatta',
        email: 'zattinha@email.com',
        password_hash: bcrypt.hashSync('0000', 8),
        is_ong: false,
        state: 'MG',
        city: 'Ipatinga',
        image: 'https://static.wikia.nocookie.net/onepunchman/images/8/81/Saitama_Anime_Profile.png/revision/latest?cb=20161002154538',
        phone: 31992324515,
        latitude: '-19.483770',
        longitude: '-42.516461',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'John Wick',
        email: 'wick@email.com',
        password_hash: bcrypt.hashSync('0000', 8),
        is_ong: false,
        state: 'MG',
        city: 'Ipatinga',
        image: 'https://observatoriodocinema.uol.com.br/wp-content/uploads/2020/08/20190518-johnwick-3-1200x675-1.jpg',
        phone: 31992324515,
        latitude: '-19.475694',
        longitude: '-42.531358',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'Cão viver',
        email: 'ong@email.com',
        password_hash: bcrypt.hashSync('0000', 8),
        is_ong: true,
        state: 'MG',
        city: 'Ipatinga',
        image: 'http://www.caoviver.com.br/wp-content/themes/caoviver2013/assets/imgs/caoviver.png',
        phone: 31992324515,
        latitude: '-19.444289',
        longitude: '-42.560084',
        created_at: new Date(),
        updated_at: new Date(),
      },
    ],
    {},
  ),

  down: () => { },
};
