const bcrypt = require('bcryptjs');

module.exports = {
  up: (QueryInterface) => QueryInterface.bulkInsert(
    'users',
    [
      {
        name: 'Vinicius',
        email: 'viniolic@email.com',
        password_hash: bcrypt.hashSync('0000', 8),
        is_ong: false,
        state: 'MG',
        city: 'Ipatinga',
        image: '../../../tmp/uploads/vini.jpeg',
        phone: 31983299996,
        latitude: '-19.483520',
        longitude: '-42.516632',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'Rafael',
        email: 'rafa@email.com',
        password_hash: bcrypt.hashSync('0000', 8),
        is_ong: false,
        state: 'MG',
        city: 'Ipatinga',
        image: '../../../tmp/uploads/rafael.jpeg',
        phone: 31989172362,
        latitude: '-19.473783',
        longitude: '-42.503646',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'Victor',
        email: 'vitinho@email.com',
        password_hash: bcrypt.hashSync('0000', 8),
        is_ong: false,
        state: 'MG',
        city: 'Ipatinga',
        image: '../../../tmp/uploads/vitao.jpeg',
        phone: 62999189082,
        latitude: '-19.480578',
        longitude: '-42.521712',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'Sarah',
        email: 'sarinha@email.com',
        password_hash: bcrypt.hashSync('0000', 8),
        is_ong: false,
        state: 'MG',
        city: 'Ipatinga',
        image: '../../../tmp/uploads/sarah.jpeg',
        phone: 33987103436,
        latitude: '-19.479076',
        longitude: '-42.512871',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'Zatta',
        email: 'zattinha@email.com',
        password_hash: bcrypt.hashSync('0000', 8),
        is_ong: false,
        state: 'MG',
        city: 'Ipatinga',
        image: '../../../tmp/uploads/zatta.jpeg',
        phone: 31998443763,
        latitude: '-19.483770',
        longitude: '-42.516461',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'John Wick',
        email: 'wick@email.com',
        password_hash: bcrypt.hashSync('0000', 8),
        is_ong: false,
        state: 'MG',
        city: 'Ipatinga',
        image: 'https://observatoriodocinema.uol.com.br/wp-content/uploads/2020/08/20190518-johnwick-3-1200x675-1.jpg',
        phone: 31992324515,
        latitude: '-19.475694',
        longitude: '-42.531358',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'Cão viver',
        email: 'ong@email.com',
        password_hash: bcrypt.hashSync('0000', 8),
        is_ong: true,
        state: 'MG',
        city: 'Ipatinga',
        image: 'http://www.caoviver.com.br/wp-content/themes/caoviver2013/assets/imgs/caoviver.png',
        phone: 31992324515,
        latitude: '-19.444289',
        longitude: '-42.560084',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'Luiz',
        email: 'luizinho@email.com',
        password_hash: bcrypt.hashSync('0000', 8),
        is_ong: true,
        state: 'MG',
        city: 'Ipatinga',
        image: '../../../tmp/uploads/luiz.jpeg',
        phone: 31987020821,
        latitude: '-19.491632',
        longitude: '-42.527848',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'Sabrina',
        email: 'bruxinha@email.com',
        password_hash: bcrypt.hashSync('0000', 8),
        is_ong: true,
        state: 'MG',
        city: 'Ipatinga',
        image: 'https://www.tenhomaisdiscosqueamigos.com/wp-content/uploads/2017/12/sabrina-aprendiz-feiticeira.jpg',
        phone: 31992324515,
        latitude: '-19.444289',
        longitude: '-42.560084',
        created_at: new Date(),
        updated_at: new Date(),
      },
    ],
    {},
  ),

  down: () => { },
};
